### ISSUE TITLE
Dear team

### ISSUE THREAD

**Issue by Lordtran87** [Blazemeter/RTEPlugin#1] opened 2018-08-13 03:44 UTC
Thank for your add-in now we can test with AS/400 v7R2 server. However, we are facing an error when we tried to send key F14. The server did not response with this step and we cannot confirm the transaction.

Pls. help us in order to resolve this issue!

Best Regards,
Ha
![f14_config](https://user-images.githubusercontent.com/10863506/44011924-cf9aa39c-9ee5-11e8-9ff0-1468b67ca9b0.PNG)
![f14_response](https://user-images.githubusercontent.com/10863506/44011926-cfdc058a-9ee5-11e8-9e59-e6879940321f.PNG)
![f14_sent](https://user-images.githubusercontent.com/10863506/44011927-d012b3a0-9ee5-11e8-8dc2-7a1749d2648c.PNG)

**Comment by rabelenda** [comment] 2018-08-13 14:33
Hi, thank you for reporting this, we have found the root cause of the issue and will release a fix shortly.

Regards.

**Comment by rabelenda** [comment] 2018-08-13 15:40
Latest release https://github.com/Blazemeter/RTEPlugin/releases/tag/v1.0.3 should fix the issue.

Regards

**Comment by rabelenda** [comment] 2018-08-13 19:06
Plugin manager has been updated to include this release. If the update does not appear you can try resetting plugin manager by using an jmx with a jsr223 sampler with following code, restarting JMeter and updating rte plugin in plugin manager window: 

```groovy
new File(System.getProperty("java.io.tmpdir") + "pmgr_cache").deleteDir()
```

**Comment by rabelenda** [comment] 2018-08-20 13:53
Closing the issue, as the issue should have been solved by latest release.

**Closed by rabelenda** 2018-08-20 13:53 UTC
